---

- name: Retrieve cribl users
  ansible.builtin.uri:
    url: http://localhost:9000/system/users
    return_content: yes
  register: users

- name: Include cribl-user-create
  ansible.builtin.include_tasks: cribl-user-create.yml
  vars:
    user: "{{ item }}"
  when:
    - users.content is defined
    - "item.name not in users.content"
  loop: "{{ cribl_users }}"
