---

- name: Create cribl user
  ansible.builtin.uri:
    url: "{{ cribl_api_base }}/system/users"
    method: POST
    headers:
      Accept: application/json
      Authorization: "Bearer {{ token }}"
    body_format: json
    # "id": "{{ lookup('community.general.random_string', length=12) }}",
    body:
      {
        "disabled": false,
        "id": "{{ user.username }}",
        "username": "{{ user.username }}",
        "email": "{{ user.email }}",
        "first": "{{ user.first }}",
        "last": "{{ user.last }}",
        "password": "{{ user.passwd }}",
        "roles": [
          "{{ user.roles }}"
        ],
      }
    return_content: yes
