---

- name: Retrieve cribl users
  ansible.builtin.uri:
    url: "{{ cribl_api_base }}/system/users"
    return_content: yes
    headers:
      Accept: application/json
      Authorization: "Bearer {{ uri_token.stdout }}"
  register: users
  failed_when: false

- name: Include cribl-user-create
  ansible.builtin.include_tasks: cribl-user-create.yml
  vars:
    user: "{{ item }}"
    # token: "{{ uri_token.content.token }}"
    token: "{{ uri_token.stdout }}"
  when:
    - users.content is defined
    - "item.username not in users.content"
  loop: "{{ cribl_users }}"
