---

# this must be after cribl starts else interfering with authentication
# and likely leave default admin as is

- name: Get API token
  ansible.builtin.uri:
    url: "{{ cribl_api_base }}/auth/login"
    headers:
      Content-Type: application/json
      Accept: application/json
    body_format: json
    body:
      {
        "username": "{{ cribl_api_user }}",
        "password": "{{ cribl_api_password }}",
      }
    return_content: yes
  register: uri_token
  failed_when: false

- name: Get API token - curl  # noqa command-instead-of-module
  ansible.builtin.shell: |
    set -o pipefail
    curl -s {{ cribl_api_base }}/auth/login -H "accept: application/json" -H "Content-Type: application/json" -d '{ "username": "{{ cribl_api_user }}", "password": "{{ cribl_api_password }}" }' | jq -r .token
  args:
    executable: /bin/bash
  register: uri_token
  changed_when: false
  failed_when: "'null' in uri_token.stdout"

- name: Import cribl-users
  ansible.builtin.import_tasks: cribl-users.yml

- name: Pause
  ansible.builtin.pause:
    seconds: 5

- name: Import cribl-packs
  ansible.builtin.import_tasks: cribl-packs.yml
  vars:
    token: "{{ uri_token.stdout }}"

# registration information from first login
# /opt/cribl/local/cribl/auth/*.dat
# /opt/cribl/local/cribl/auth/676f6174733432.dat
# salt?
# /opt/cribl/local/cribl/auth/cribl.secret

# https://docs.cribl.io/stream/version-control/
- name: Configure Cribl gitignore
  ansible.builtin.lineinfile:
    path: "{{ cribl_home }}/.gitignore"
    line: "{{ item }}"
  loop:
    # ansible backup files
    - '*.*-*-*@*:*:*~'
  notify:
    - Restart Cribl
