---

# this must be after cribl starts else interfering with authentication
# and likely leave default admin as is

- name: Recover admin password hash
  ansible.builtin.command: awk -F'[:,}"]' '/"admin",/ { print $35}' /opt/cribl/local/cribl/auth/users.json
  changed_when: false
  register: admin_pass

- name: Set fact cribl_users_admin
  ansible.builtin.set_fact:
    cribl_users_admin:
      - username: admin
        first: admin
        last: admin
        email: admin
        roles: admin
        passwd: "{{ admin_pass.stdout }}"
- name: Set fact cribl_users2
  ansible.builtin.set_fact:
    cribl_users2: "{{ cribl_users_admin + cribl_users }}"
- name: Debug | cribl_users
  ansible.builtin.debug:
    var: cribl_users2

- name: Configure users
  ansible.builtin.template:
    src: users.json.j2
    dest: "{{ cribl_home }}/local/cribl/auth/users.json"
    mode: '0600'
    owner: "{{ cribl_user }}"
    backup: "{{ cribl_backup | default('no') }}"

# registration information from first login
# /opt/cribl/local/cribl/auth/*.dat
# /opt/cribl/local/cribl/auth/676f6174733432.dat
# salt?
# /opt/cribl/local/cribl/auth/cribl.secret

# https://docs.cribl.io/stream/version-control/
- name: Configure Cribl gitignore
  ansible.builtin.lineinfile:
    path: "{{ cribl_home }}/.gitignore"
    line: "{{ item }}"
  loop:
    # ansible backup files
    - '*.*-*-*@*:*:*~'
  notify:
    - Restart Cribl
