---

# this must be after cribl starts else interfering with authentication
# and likely leave default admin as is

- name: Import cribl-users
  ansible.builtin.import_tasks: cribl-users.yml

# registration information from first login
# /opt/cribl/local/cribl/auth/*.dat
# /opt/cribl/local/cribl/auth/676f6174733432.dat
# salt?
# /opt/cribl/local/cribl/auth/cribl.secret

# https://docs.cribl.io/stream/version-control/
- name: Configure Cribl gitignore
  ansible.builtin.lineinfile:
    path: "{{ cribl_home }}/.gitignore"
    line: "{{ item }}"
  loop:
    # ansible backup files
    - '*.*-*-*@*:*:*~'
  notify:
    - Restart Cribl
